### PR TITLE
Init markdown-parser and fill containers

### LINKED ISSUE #13: Fix the missing <p> tag in in the abstract section
As I mentioned in  #12, there's an unexpected `<p>` tag in the `abstract` section of `tests/markdown001.html`. It turns out that `bikeshed` would [use a markdown-parser](https://github.com/tabatkins/bikeshed/blob/76c0936a72a830622de27fbabee0556ba1c4023a/bikeshed/metadata.py#L278) to [turn text elements into block-level elements](https://github.com/tabatkins/bikeshed/blob/76c0936a72a830622de27fbabee0556ba1c4023a/bikeshed/markdown/markdown.py#L371). This issue could be fixed by implementing the `markdown` module.

### PR DESCRIPTION
**Pull request by whichxjy**
1. A simple markdown-parser is implemented to fix #13.

2. Information about the editor is filled in the metadata section.

### CODE REVIEW

File: src/markdown.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+pub fn parse(lines: &[String]) -> Vec<String> {
+    let tokens = tokenize(lines);
+    parse_tokens(&tokens)
+}
+
+enum Token {
+    Text(String),
+}
+
+// Turn lines of text into block tokens, which'll be turned into MD blocks later.
```
Comment (emilio) [inline src/markdown.rs:198]: Is the idea that this will become more complex in the future? A tokenizer with just one token type doesn't seem very useful.

File: src/markdown.rs [hunk 2]
```diff
@@ -24,16 +28,51 @@ fn tokenize(lines: &[String]) -> Vec<Token> {
...
+    I: Iterator<Item = &'a Token>,
+{
+    let mut lines = vec![format!("<p>{}\n", text)];
+
+    loop {
+        let curr = if let Some(token) = stream.next() {
+            token
+        } else {
+            break;
+        };
```
Comment (emilio) [inline src/markdown.rs:428]: `while let Some(token) = stream.next() {` instead of this?

**Comment by whichxjy** [comment]
Basic features of Markdown are implemented.

File: src/markdown.rs [hunk 3]
```diff
@@ -24,16 +28,51 @@ fn tokenize(lines: &[String]) -> Vec<Token> {
...
     let mut lines = Vec::new();
 
-    for token in tokens {
-        let Token::Text(text) = token;
-        lines.extend(parse_paragraph(text));
+    let mut prev = Token::Blank;
+    let mut stream = tokens.into_iter();
+
+    loop {
+        let curr = if let Some(token) = stream.next() {
```
Comment (emilio) [inline src/markdown.rs]: While let.

File: src/markdown.rs [hunk 4]
```diff
@@ -38,12 +49,22 @@ fn parse_tokens(tokens: &[Token]) -> Vec<String> {
...
-            prev = curr.clone();
+            Token::Block(line) => {
+                lines.push(line.clone());
+                prev = curr.clone();
+            }
+            Token::Text(line) => {
+                if prev == Token::Blank {
+                    lines.extend(parse_paragraph(line, &mut stream, &mut prev));
+                } else {
+                    prev = curr.clone();
```
Comment (emilio) [inline src/markdown.rs]: Do you need the clone here? It seems you could have just `prev = curr` unless I'm missing something.

File: src/boilerplate.rs [hunk 5]
```diff
@@ -206,43 +206,39 @@ pub fn add_spec_metadata_section(doc: &mut Spec) {
...
-        let a_el = html::node::new_a(
-            btreemap! {
-                "class" => "u-url".to_owned(),
-                "href" => version.to_owned(),
-            },
-            version,
-        );
-        let dd_el = wrap_in_dd_node(a_el);
-        dl_el.append(dd_el);
+        md_list.extend(vec![
```
Comment (emilio) [inline src/boilerplate.rs]: I'd just `push(key_to_dt_node(..))` and `push(wrap_in_dd_node(..))`, but no big deal.

File: src/metadata/metadata.rs [hunk 6]
```diff
@@ -259,7 +268,9 @@ impl Metadata {
     }
 
     pub fn compute_implicit_metadata(&mut self) {
-        if self.canonical_url.as_ref().map_or(true, |url| url == "ED") {
+        if self.canonical_url.as_ref().map_or(true, |url| url == "TR") && self.tr.is_some() {
```
Comment (emilio) [inline src/metadata/metadata.rs]: Hmm, so this overrides the canonical url if already computed? That seems wrong?

File: src/metadata/metadata.rs [hunk 7]
```diff
@@ -158,6 +159,15 @@ impl Metadata {
                 let val = val.to_owned();
                 self.group = Some(val);
             }
+            "Infer CSS Dfns" => {
+                let val = match parse::parse_bool(val) {
+                    Ok(val) => val,
+                    Err(_) => {
+                        die!("The \"Infer Css Dfns\" field must be boolish. Got: {}.", val; line_num)
```
Comment (emilio) [inline src/metadata/metadata.rs]: nit: Casing differs here.

File: src/metadata/parse.rs [hunk 8]
```diff
@@ -25,7 +29,7 @@ pub fn parse_boilerplate(val: &str) -> Result<BoolSet<String>, &'static str> {
             boilerplate.insert(pieces[1].clone(), false);
         } else {
             // <section> <boolish>
-            if let Some(on_off) = boolish_to_bool(&pieces[1]) {
+            if let Ok(on_off) = boolish_to_bool(&pieces[1]) {
```
Comment (emilio) [inline src/metadata/parse.rs]: Can this do just `let on_off = boolish_to_bool(&pieces[1])?;`

File: src/metadata/metadata.rs [hunk 9]
```diff
@@ -164,7 +164,7 @@ impl Metadata {
                 let val = match parse::parse_bool(val) {
                     Ok(val) => val,
                     Err(_) => {
-                        die!("The \"Infer Css Dfns\" field must be boolish. Got: {}.", val; line_num)
+                        die!("The \"Infer CSS Dfns\" field must be boolish. Got: {}.", val; line_num)
```
Comment (emilio) [inline src/metadata/metadata.rs]: Ah, you fixed this here :)

File: src/markdown.rs [hunk 10]
```diff
@@ -38,6 +38,58 @@ impl Token {
...
+    fn new(tokens: &'a [Token]) -> Self {
+        TokenStream {
+            tokens,
+            curr: 0,
+            before: Token::new_blank(),
+            after: Token::new_end(),
+        }
+    }
+
+    fn move_to_next(&mut self) {
```
Comment (emilio) [inline src/markdown.rs]: maybe `advance()`?

File: src/html/node.rs [hunk 11]
```diff
@@ -79,6 +79,20 @@ pub fn insert_attr<T: Into<String>>(el: &NodeRef, attr_name: &str, attr_val: T)
...
 
+pub fn get_attr(el: &NodeRef, attr_name: &str) -> Option<String> {
+    let data = match el.data() {
+        NodeData::Element(data) => data,
+        _ => return None,
+    };
+
+    let attributes = data.attributes.borrow();
+
+    match attributes.get(LocalName::from(attr_name)) {
```
Comment (emilio) [inline src/html/node.rs]: nit: just `attribute.get(..).map(ToOwned::to_owned)`

File: src/markdown.rs [hunk 12]
```diff
@@ -90,6 +91,24 @@ impl<'a> TokenStream<'a> {
     }
 }
 
+fn is_single_line_heading(line: &str) -> bool {
+    lazy_static! {
+        // regex for heading
+        static ref HEADING_REG: Regex = Regex::new(r"^(?P<left_prefix>#{1,5})\s+[^#]+((?P<right_prefix>#{1,5})\s*\{#[^}]+\})?\s*$").unwrap();
+    }
+
+    if let Some(caps) = HEADING_REG.captures(line) {
```
Comment (emilio) [inline src/markdown.rs]: I'd early return here, so:

```
let caps = match HEADING_REG.captures(line) {
    Some(c) => c,
    None => return false,
};
```

And so on.

But it's just stylistic so no big deal.

File: src/markdown.rs [hunk 13]
```diff
@@ -161,6 +186,33 @@ fn parse_tokens(tokens: &[Token]) -> Vec<String> {
 // NOTE: When a particular section-parsing function is over, the current token
 // in the stream should be the last token of the section.
 
+fn parse_single_line_heading(stream: &mut TokenStream) -> String {
```
Comment (emilio) [inline src/markdown.rs:290]: It is a bit odd to have a tokenizer that leaves only the token kind instead of some better parsed representation, but I guess it's ok.

File: src/markdown.rs [hunk 14]
```diff
@@ -169,8 +171,26 @@ fn is_single_line_heading(line: &str) -> bool {
     }
 }
 
+fn extract_def_token_kind(line: &str) -> Option<TokenKind> {
+    lazy_static! {
+        // regex for definition item
+        static ref DEF_REG: Regex = Regex::new(r"^(?P<prefix>:{1,2})").unwrap();
+    }
+
+    if let Some(caps) = DEF_REG.captures(line) {
```
Comment (emilio) [inline src/markdown.rs]: `let caps = DEF_REG.captures(line)?;`

Then deindent the rest.

File: src/html/node.rs [hunk 15]
```diff
@@ -169,3 +169,23 @@ pub fn copy_content(from_el: &NodeRef, to_el: &NodeRef) {
         to_el.append(from_el_child.clone());
     }
 }
+
+pub fn deep_clone(el: &NodeRef) -> NodeRef {
+    let data = match el.data() {
```
Comment (emilio) [inline src/html/node.rs]: Is `NodeData` not clonable?

File: src/boilerplate.rs [hunk 16]
```diff
@@ -309,4 +309,118 @@ pub fn fill_toc_section(doc: &mut Spec) {
     );
     h2_el.append(html::node::new_text("Table of Contents"));
     container.as_node().append(h2_el);
+
+    // Each cell stores the reference to <ol> of a particular heading level.
+    // Relation: <h[level]> => ol_cells[level - 2], where 2 <= level <= 6.
+    let mut ol_cells: Vec<Option<NodeRef>> = vec![None; 6];
```
Comment (emilio) [inline src/boilerplate.rs]: Could be just an `[Option<NodeRef>; 6]` right?

File: src/markdown.rs [hunk 17]
```diff
@@ -204,41 +226,40 @@ fn tokenize_lines(lines: &[String], tab_size: u32) -> Vec<Token> {
         static ref HTML_BLOCK_REG: Regex = Regex::new(r"<").unwrap();
     }
 
+    let token_factory = TokenFactory::new(tab_size);
```
Comment (emilio) [inline src/markdown.rs]: You could have just made this something like:

```
let make_token = |token_kind, line| {
    let indent_level = get_indent_level(&line, tab_size);
    Token { ... }
};
```

:)

**Comment by whichxjy** [comment]
@emilio Could you review this PR? (It might be too many commits in a single PR.)

**Review by emilio — COMMENTED** [review]
Sorry, I had started to review but then had to go, and forgot to publish. I think a lot of the comments I had have been addressed in follow-up commits, so please disregard them.

It looks generally good. For my own reference, I need to start reviewing again at f0b88732eebb037d7a4ab193e5a0c03f8563b10e, I'll try to do that early tomorrow.

File: src/metadata/metadata.rs (hunk 6 above)
Comment (whichxjy) [reply src/metadata/metadata.rs]: In `bikeshed`, if the canonical url is none or equals to "TR", it would be assigned the value of "TR" metadata when the "TR" metadata isn't none.

File: src/boilerplate.rs (hunk 16 above)
Comment (whichxjy) [reply src/boilerplate.rs]: I edit it to `let mut ol_cells: [Option<NodeRef>; 6] = [None; 6];` and get this error message: the trait bound `std::option::Option<kuchiki::tree::NodeRef>: std::marker::Copy` is not satisfied.

Is it necessary to write something like `let mut ol_cells: [Option<NodeRef>; 6] = [None, None, None, None, None, None];`?

Comment (emilio) [reply src/boilerplate.rs]: Hmm, either that or `Default::default()`, I think.

File: src/metadata/mod.rs [hunk 18]
```diff
@@ -172,6 +174,16 @@ impl Metadata {
                 };
                 self.indent = Some(val);
             }
+            "Markup Shorthands" => {
+                let val = match parse::parse_markup_shorthands(val) {
+                    Ok(val) => val,
+                    Err(_) => {
+                        die!("Markup shorthands metadata pieces are a markup markup shorthand category and a boolean. \
+                            Got: {}.", val; line_num)
```
Comment (emilio) [inline src/metadata/mod.rs]: indentation looks a bit odd here.

File: src/metadata/parse.rs [hunk 19]
```diff
@@ -251,6 +251,37 @@ pub fn parse_level(val: &str) -> String {
...
+            .map(|piece| piece.trim().to_lowercase())
+            .collect::<Vec<String>>();
+
+        if pieces.len() != 2 {
+            return Err("wrong markup shorthand piece format");
+        }
+
+        match pieces[0].as_str() {
+            "algorithm" | "biblio" | "css" | "dfn" | "idl" | "markdown" | "markup" => {
+                if let Ok(on_off) = boolish_to_bool(&pieces[1]) {
```
Comment (emilio) [inline src/metadata/parse.rs]: just `let on_off = boolish_to_bool(&pieces[1])?;`

File: src/util/boolset.rs [hunk 20]
```diff
@@ -15,6 +15,7 @@ where
 {
     map: HashMap<K, bool>,
     default_val: bool,
+    pub is_default: bool,
```
Comment (emilio) [inline src/util/boolset.rs]: Why is this needed rather than something checking `self.map.is_empty()`? seems like that would avoid having to check for `is_default` before extending the map and so on.

File: src/boilerplate.rs [hunk 21]
```diff
@@ -68,17 +68,56 @@ pub fn retrieve_boilerplate_with_info(
...
+        }
+    }
+}
+
+fn get_container(doc: &Spec, tag: &str) -> Option<NodeRef> {
+    if !doc.md.boilerplate.get(tag) {
+        return None;
+    }
+
+    match doc.containers.get(tag) {
```
Comment (emilio) [inline src/boilerplate.rs]: Just `doc.containers.get(tag).cloned()`.

File: src/boilerplate.rs [hunk 22]
```diff
@@ -68,17 +68,56 @@ pub fn retrieve_boilerplate_with_info(
...
+        None => None,
+    }
+}
+
+fn get_container_or_head(doc: &Spec, tag: &str) -> Option<NodeRef> {
+    if !doc.md.boilerplate.get(tag) {
+        return None;
+    }
+
+    match doc.containers.get(tag) {
```
Comment (emilio) [inline src/boilerplate.rs]: Same here.

**Review by emilio — APPROVED** [review]
I have a question about the bool set's `is_default`, but the rest looks fine otherwise. Thank you!

File: src/boilerplate.rs [hunk 23]
```diff
@@ -84,21 +84,18 @@ fn get_container(doc: &Spec, tag: &str) -> Option<NodeRef> {
...
     }
 
-    match doc.containers.get(tag) {
-        Some(container) => Some(container.clone()),
-        None => Some(doc.head().clone()),
-    }
+    doc.containers
+        .get(tag)
+        .cloned()
+        .or(Some(doc.head().clone()))
```
Comment (emilio) [inline src/boilerplate.rs:98]: This should probably do `.or_else(..)`, otherwise you're calling `clone()` and such even if the container exists.

**Review by emilio — APPROVED** [review]
Thank you!
